config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: :show
  resources :tweets, only: [:create, :destroy, :show] do
    resources :likes, only: [:create, :destroy, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :tweet, optional: true
  mount_uploader :url, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, presence: true, uniqueness: {scope: :tweet_id}
  validates :tweet_id, presence: true
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :no_image
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy


  mount_uploader :video, VideoUploader

  def no_image(images_attributes)
    images_attributes[:url].blank?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
  has_many :likes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}" 
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_tweet, only: [:create, :destroy]
  def create
    @like = current_user.likes.create(like_params)
    redirect_to tweet_path(@tweet)
  end

  def destroy
    @like = Like.find_by(like_params, user_id: current_user.id)
    @like.destroy
    redirect_to tweet_path(@tweet)
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
  def like_params
    params.permit(:tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
 
  def index
    # @tweets = Tweet.includes(:user).order("created_at DESC")
    @tweets = Tweet.all.order('created_at ASC')
  end

  def new
    @tweet = Tweet.new
    @tweet.images.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      flash.now[:alert] = 'エラー : 必須項目を入力してください。'
      render :new
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy    
  end

  def edit
    @tweet.images.new
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:video, :text, :title, images_attributes: [:url, :_destroy, :id]).merge(user_id: current_user.id)
  end
  def set_tweet
    @tweet = Tweet.find(params[:id])
    @images = @tweet.images
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NaPuRi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a{:href => "/"}
            NaPuRi
            %h3 〜自分だけの思い出を残そう〜
        - if user_signed_in?
          .user_nav.grid-6
            %span
              = current_user.nickname
              %ul.user__info
                %li
                  = link_to "MyPage", "/users/#{current_user.id}"
                  = link_to "LogOut", destroy_user_session_path, method: :delete
            = link_to "POST", new_tweet_path, class: "post"
        - else
          .grid-6
            = link_to "LogIn", new_user_session_path, class: "post"
            = link_to "SignUp", new_user_registration_path, class: "post"
    = yield
    %footer
      %p
        Copyright NaPuRi 2020.

app/views/tweets/_form.html.haml
%h2
  Images
#diary-image
  #previews
  .diary-image__box#image-box__container
    %i.fa.fa-camera-retro
    %p.diary-image__box__text
      クリックしてファイルをアップロード
    =form.fields_for :images do |i|
      .diary-image__box__input{"data-index": "#{i.index}"}
        = i.file_field :image, type: 'file', name: "tweet[images_attributes][#{i.index}][url]",class:"js-file", id:"tweet_images_attributes_0_url"
        %label{for: "img-file"}
%h2
  Video
  = form.file_field :'video', accept: 'video/*'

%h2
  Title
  = form.text_field :title,  rows: "1"
%h2
  Diary
  = form.text_area :text, placeholder: "投稿内容", rows: "10"
  = form.submit '投    稿'

app/views/tweets/_tweet.html.haml
- if user_signed_in? && current_user.id == tweet.user_id
  .TweetList-index
    .detail
      %ul.detail_lists
        %li
          = link_to '▶︎ Details', tweet_path(tweet.id), method: :get ,class: "detail_list"
    .TweetList__date
      .date_time
        .date_time__y
          = tweet.created_at.strftime('%Y年')
          %br
        .date_time__m
          - require 'date'
          - dw = ["日", "月", "火", "水", "木", "金", "土"]
          = tweet.created_at.strftime("%m月%d日(%a)")

    .TweetList__title
      題 名
      .text__box
        = link_to edit_tweet_path(tweet.id), method: :get do
          = tweet.title

    .TweetList__text
      日 記
      .text__box
        %p
          = simple_format(tweet.text)

    .TweetList__image
      画 像
      .image__box
        .image__list
          = link_to edit_tweet_path(tweet.id), method: :get do
            %figure.js-img
              - tweet.images.each do |i|
                = image_tag i.url.url margin:"15px"

    .TweetList__video
      動 画
      .video__box
        = link_to tweet.video_url.to_s do
          .video__box__url
            = video_tag tweet.video_url.to_s,width: "75%", height: "340px", controls: true, autobuffer: true

    .TweetList__name
      %span.name
        %a{:href => "/users/#{tweet.user.id}"}
          作者：
          = tweet.user.nickname

app/views/tweets/before_show.html.haml
.contents.row
  .content_post{:style => "background-image: url(#{@tweet.image});"}
    - if user_signed_in? && current_user.id == @tweet.user_id
      .more
        %span= image_tag 'arrow_top.png'
        %ul.more_list
          %li
            = link_to 'Edit', edit_tweet_path(@tweet.id), method: :get
          %li
            = link_to 'Delete', tweet_path(@tweet.id), method: :delete
    %p= @tweet.text
    %span.name
      %a{:href => "/users/#{@tweet.user.id}"}
        %span 投稿者
        = @tweet.user.nickname
  .container
    - if current_user
      = form_with(model: [@tweet, @comment], local: true) do |form|
        = form.text_area :text, placeholder: "コメントする", rows: "2"
        = form.submit "SEND"
    - else
      %strong
        %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    .like_button
      - if current_user.likes.find_by(tweet_id: @tweet.id)
        = link_to tweet_like_path(@tweet), method: :delete do
          %span.fa.fa-heart.like-btn いいね
      - else
        = link_to tweet_likes_path(@tweet), method: :post do
          %span.fa.fa-heart.like-btn-unlike いいね
    .comments
      %h4 ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname, "/users/#{comment.user_id}"
              ：
            = comment.text

app/views/tweets/create.html.haml
.contents.row
  .success
    %h3 投稿完了!!
    %a.btn{:href => "/"} ホーム画面へ戻る

app/views/tweets/destroy.html.haml
.contents.row
  .success
    %h3 削除完了!!
    %a.btn{:href => "/"} ホーム画面へ戻る

app/views/tweets/edit.html.haml
.contents-row
  .container
    = form_with(model: @tweet, local: true) do |form|
      %h3 Edit
      %h2
        Images
      #diary-image
        #previews
          - @images.each_with_index do |img, i|
          
            -if img.persisted?
              #parent{data: {index: i}}
                = image_tag img.url.url, class:"js-img", id: "js-img_#{i}"
                .js-remove{"data-index": "#{i}", id: "remove_#{i}"} 削除

        .diary-image__box#image-box__container
          =form.fields_for :images do |i|
            .diary-image__box__input{"data-index": "#{i.index}"}
              = i.file_field :image, name: "tweet[images_attributes][#{i.index}][url]",class:"js-file", id:"tweet_images_attributes_#{i.index}_url"
              = i.check_box :_destroy ,"data-index": "#{i.index}",class:"hidden-destroy"
              %label{for: "img-file"}
          %i.fa.fa-camera-retro
          %p.diary-image__box__text
            クリックしてファイルをアップロード
              
      %h2
        Video
        = form.file_field :'video'
      %h2
        Title
        = form.text_field :title,  rows: "1"
      %h2
        Diary
        = form.text_area :text, placeholder: "投稿内容", rows: "10"
        = form.submit '投    稿'

app/views/tweets/index.html.haml
.contents_row
  - @tweets.each do |tweet|
    = render partial: "tweet", locals: { tweet: tweet }

app/views/tweets/new.html.haml
.contents-row
  .container
    = form_with(model: @tweet, local: true) do |form|
      %h3 POST
      = render partial: "form", locals: { form: form }

app/views/tweets/show.html.haml
.contents-row
  .TweetList
    .TweetList__date
      .date_time
        .date_time__y
          = @tweet.created_at.strftime('%Y年')
          %br
        .date_time__m
          - require 'date'
          - dw = ["日", "月", "火", "水", "木", "金", "土"]
          = @tweet.created_at.strftime("%m月%d日(%a)")

      .choice
        %ul.choice_lists
          %li
            = link_to '▶︎ Details', tweet_path(@tweet.id), method: :get ,class: "choice_list"
          - if user_signed_in? && current_user.id == @tweet.user_id
            %li
              = link_to '▶︎ Edit', edit_tweet_path(@tweet.id), method: :get ,class: "choice_list"
            %li
              = link_to '▶︎ Delete', tweet_path(@tweet.id), method: :delete ,class: "choice_list"

    .TweetList__title
      題 名
      .text__box
        = link_to edit_tweet_path(@tweet.id), method: :get do
          = @tweet.title

    .TweetList__text
      日 記
      .text__box
        %p
          = simple_format(@tweet.text)

    .TweetList__image
      画 像
      .image__box
        .image__list
          = link_to edit_tweet_path(@tweet.id), method: :get do
            %figure.js-img
              - @tweet.images.each do |i|
                = image_tag i.url.url margin:"15px"

    .TweetList__video
      動 画
      .video__box
        = link_to @tweet.video_url.to_s do
          .video__box__url
            = video_tag @tweet.video_url.to_s,width: "75%", height: "340px", controls: true, autobuffer: true
  
    .container
      - if current_user
        = form_with(model: [@tweet, @comment], local: true) do |form|
          = form.text_area :text, placeholder: "コメントする", rows: "2"
          = form.submit "SEND"
      - else
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      .like_button
        - if current_user.likes.find_by(tweet_id: @tweet.id)
          = link_to tweet_like_path(@tweet), method: :delete do
            %span.fa.fa-heart.like-btn いいね
        - else
          = link_to tweet_likes_path(@tweet), method: :post do
            %span.fa.fa-heart.like-btn-unlike いいね
      .comments
        %h4 ＜コメント一覧＞
        - if @comments
          - @comments.each do |comment|
            %p
              %strong
                = link_to comment.user.nickname, "/users/#{comment.user_id}"
                ：
              = comment.text

    .TweetList__name
      %span.name
        %a{:href => "/users/#{@tweet.user.id}"}
          作者：
          = @tweet.user.nickname

app/views/tweets/update.html.haml
.contents.row
  .success
    %h3 更新完了!!
    %a.btn{:href => "/"} ホーム画面へ戻る

app/views/users/show.html.haml
.contents-row
  %p.s_Page
    = @nickname
    's Diary
  - @tweets.each do |tweet|
    - if user_signed_in? && current_user.id == tweet.user_id
      .TweetList
        .detail
          %ul.detail_lists
            %li
              = link_to '▶︎ Details', tweet_path(tweet.id), method: :get ,class: "detail_list"
        .TweetList__date
          .date_time
            .date_time__y
              = tweet.created_at.strftime('%Y年')
              %br
            .date_time__m
              - require 'date'
              - dw = ["日", "月", "火", "水", "木", "金", "土"]
              = tweet.created_at.strftime("%m月%d日(%a)")

        .TweetList__title
          題 名
          .text__box
            = link_to edit_tweet_path(tweet.id), method: :get do
              = tweet.title

        .TweetList__text
          日 記
          .text__box
            %p
              = simple_format(tweet.text)

        .TweetList__image
          画 像
          .image__box
            .image__list
              = link_to edit_tweet_path(tweet.id), method: :get do
                %figure.js-img
                  - tweet.images.each do |i|
                    = image_tag i.url.url margin:"15px"

        .TweetList__video
          動 画
          .video__box
            = link_to tweet.video_url.to_s do
              .video__box__url
                = video_tag tweet.video_url.to_s,width: "75%", height: "340px", controls: true, autobuffer: true

        .TweetList__name
          %span.name
            %a{:href => "/users/#{tweet.user.id}"}
              作者：
              = tweet.user.nickname